[project]
name = "arborinth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Erwin Janssen", email = "code@erwinjanssen.nl" }
]
requires-python = ">=3.12"
dependencies = ["click"]

[project.scripts]
arborinth = "arborinth.cli:main"

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.ruff.lint]
# Enable all rules by default
select = ["ALL"]

# Fix all fixable violations by default
fixable = ["ALL"]
unfixable = []

ignore = [
    "D213", # `multi-line-summary-second-line` (conflicts with D212)
    "D203",  # `incorrect-blank-line-before-class` (conflicts with D211)
    "COM812",  # `missing-trailing-comma` (conflicts with formatter)
]

[tool.ruff.lint.pydocstyle]
convention = "google"
