[project]
name = "arborinth"
version = "0.1.0"
description = "Safely run untrusted code on your repository in isolated, controlled environments"
readme = "README.md"
authors = [
    { name = "Erwin Janssen", email = "code@erwinjanssen.nl" }
]
requires-python = ">=3.12"
dependencies = ["click"]

[project.scripts]
arborinth = "arborinth.cli:main"

[build-system]
requires = ["uv_build>=0.9.30,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.mdformat]
# Apply consecutive numbering to ordered lists, instead of using `1.` for each
# item.
number = true

[tool.ruff.lint]
# Enable all rules by default
select = ["ALL"]

# Fix all fixable violations by default
fixable = ["ALL"]
unfixable = []

ignore = [
    "D213", # `multi-line-summary-second-line` (conflicts with D212)
    "D203",  # `incorrect-blank-line-before-class` (conflicts with D211)
    "COM812",  # `missing-trailing-comma` (conflicts with formatter)

    # This rule triggers every time a variable is used in `subprocess.run`,
    # warning that the input should be validated. However, there does not seem
    # to be a way to do so in such a way that this rule is satisfied. This rule
    # is therefore disabled.
    "S603",  # `subprocess-without-shell-equals-true`

    # This rule is too strict, as it requires all executable paths to be
    # hardcoded. There is little value in this, and it is not practical.
    # Hardcoded paths also prevent the use of tools like Nix
    "S607",  # `start-process-with-partial-path`
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "S101",  # `assert` (tests should use assert statements)
]

[tool.ruff.lint.pydocstyle]
convention = "google"
